spring:

  datasource:
    url: jdbc:h2:mem:formlogin
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
